Fix AttributeError in ControlArm.__repr__ method
Change reference from self.additional_attachments (which doesn't exist)
to self.attachment_points (the correct attribute name).

This fixes the error:
AttributeError: 'ControlArm' object has no attribute 'additional_attachments'

All tests now passing.